version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python bot.py
    volumes:
      - .:/app
    working_dir: /app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python index.py
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - ./backend/.env
